### PR TITLE
fix: ci failure from gitpython

### PR DESCRIPTION
**Pull request by JJJ000**
Description of changeset: 
fix: ci failure from gitpython

Test Plan: 
verify in ci

### CODE REVIEW

**Comment by csharplus** [comment]
@JJJ000 the CI build still failed.

**Comment by csharplus** [comment]
@JJJ000 CI still failed

**Comment by csharplus** [comment]
@JJJ000 do you know why a build for Apple is also part of the CI build:
Screen Shot 2022-03-01 at 9 56 26 PM

**Comment by JJJ000** [comment]
> @JJJ000 do you know why a failed build for Apple is also part of the CI:
> 
> Screen Shot 2022-03-01 at 9 56 26 PM

working on it, looks like at least part of the issue has been fixed

**Comment by csharplus** [comment]
> > @JJJ000 do you know why a failed build for Apple is also part of the CI:
> > Screen Shot 2022-03-01 at 9 56 26 PM
> 
> working on it, looks like at least part of the issue has been fixed

Right, the major ones related to Python and R seem to have been fixed.  Let's resolve this remaining build failure.

**Comment by JJJ000** [comment]
> > > @JJJ000 do you know why a failed build for Apple is also part of the CI:
> > > Screen Shot 2022-03-01 at 9 56 26 PM
> > 
> > 
> > working on it, looks like at least part of the issue has been fixed
> 
> Right, the major ones related to Python and R seem to have been fixed. Let's resolve this remaining build failure.
Issue has been fixed. The major issue is that beautifulsoup4 does not support python 3.10. Somehow travis does not take python version configuration. Hard coded to 3.9 fix the issue.

**Comment by csharplus** [comment]
> > > > @JJJ000 do you know why a failed build for Apple is also part of the CI:
> > > > Screen Shot 2022-03-01 at 9 56 26 PM
> > > 
> > > 
> > > working on it, looks like at least part of the issue has been fixed
> > 
> > 
> > Right, the major ones related to Python and R seem to have been fixed. Let's resolve this remaining build failure.
> > Issue has been fixed. The major issue is that beautifulsoup4 does not support python 3.10. Somehow travis does not take python version configuration. Hard coded to 3.9 fix the issue.

Nice, the build passed.  Let's merge to fix the build issue.

**Review by csharplus — APPROVED** [review]
LGTM.

**Pull request merged**
