### PR TITLE
Don't use a dot delimiter for naming auth_provider blueprints

### LINKED ISSUE #594: Flask blueprints no longer allow dots in names
First - thanks for making this project public. It's really useful, and I'm working through setting an instance up for our data science team. While implementing a new `auth_provider` method for our SSO I encountered a bug that should be affecting all new users on Flask >= 2.0.1. The `auth_provider` blueprint name can no longer contain a dot (see https://github.com/pallets/flask/pull/4045). I'll submit a small PR to fix this.

### PR DESCRIPTION
**Pull request by mdshw5**
This pull request fixes #594. 

Description of changeset: Changed the naming scheme for `auth_provider` blueprints.

Test Plan: It seems like the test suite is broken, but in testing this appears to fix the issue.

### CODE REVIEW

**Comment by mdshw5** [comment]
Hey @bulam - sorry for the direct mention, but this bug prevents new users from running the knowledge repo Flask app under the latest Flask framework. The fix provided in my PR (or another similar solution) resolves this blocking issue. As it's not clear who maintains this project please let me know if there's someone else I should loop in. Thanks!

**Comment by jpzhangvincent** [comment]
Can we merge this PR? I also failed to launch the app after upgrading to the 0.9 version

**Review by naoyak — APPROVED** [review]
Thanks!

**Comment by naoyak** [comment]
Hi @mdshw5 - would you mind rebasing this PR on the latest upstream master?

**Comment by mdshw5** [comment]
Sure @naoyak. I'll push the rebased branch shortly.

**Comment by mdshw5** [comment]
@naoyak this is ready for merging.

**Pull request merged**
