### PR TITLE
Rewrite to rmd.py converter to enable javascript plotly plots in Rmarkdown

### PR DESCRIPTION
**Pull request by dorianbrown**
This pull request replaces the previous one on this issue (#393), which can't be used any more since I accidentally deleted the original branch/repository. I was able to restore the changes to a new one, so this should contain the same changes.

Regarding the changes:
- Replace `knitr` with `rmarkdown::render`, which is a much more capable parser for Rmd notebooks.
- Add necessary javascript header with plotly libraries on relevant plotly posts.
- Added two Rmd notebooks to the test posts, a vanilla Rmd and a plotly Rmd notebook.
- Added package dependencies to `travis.yml` and `appveyor.yml`

Since this code is about 2.5 years old I'd like to review it again myself, but I'm also very curious to hear what other steps would need to be taken to get this merged!

### CODE REVIEW

**Comment by bulam** [comment]
@dorianbrown Thanks for the contribution! This looks good to me. If you have tested the plotly functionality and made sure it's working as expected we're good to merge

**Comment by dorianbrown** [comment]
Happy to help! All the cases I've tried so far work perfectly, so I'd say it's ready to be merged.

**Comment by bulam** [comment]
@dorianbrown Awesome. Feel free to merge whenever you're ready :)

**Comment by dorianbrown** [comment]
I'm looking for a way to merge it, but I don't think I have the permission to. 

Are you able to merge it?

**Comment by bulam** [comment]
Oh got it. Just merged!

**Pull request merged**
