### PR TITLE
add launch config for local test

### PR DESCRIPTION
**Pull request by JJJ000**
Description of changeset: 

add launch config for local test for local debug

Test Plan: 
[x]local build

@csharplus

### CODE REVIEW

**Review by csharplus — APPROVED** [review]
LGTM.

**Comment by csharplus** [comment]
@JJJ000 the CI build was failed somehow.  Please take a look.

**Comment by JJJ000** [comment]
potential blocker due to macos 12 upgrade. https://github.blog/changelog/2022-06-13-github-actions-macos-12-for-github-hosted-runners-is-now-generally-available/ root cause is under investigation.

**Comment by csharplus** [comment]
@JJJ000 all passed!

**Pull request merged**
