### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by FvD**
To play around with knowledge-repo it would be helpful to have a Dockerfile. This one should work after #57 is solved. Right now knowledge-repo installs correctly, but I cannot `init` a local repo because a github ssh key is required.

### CODE REVIEW

**Comment by matthewwardrop** [comment]
Hooray! Our first external contribution 🎆  Thank you!

Internally we've started experimenting with deploying the knowledge-repo using Docker too, but are still sorting a few odds and ends out. As you say, though, it might make a lot of sense to include a Dockerfile earlier rather than later for testing purposes. If we are going to include one we should probably also add clear documentation for how to set up a docker image that runs a pre-existing knowledge repository (either on the host filesystem mounted into the Docker image or one generated and/or downloaded in the application itself).

As for this Dockerfile, we're more than happy to accept the contribution to help people play around with it. You'll need to add the following line somewhere near the top:
`EXPOSE 7000`
which is the port which the knowledge-repo server uses by default. Once you've played around with a bit, and it looks good, ping me for another review :).

I do wonder though whether this is actually easier to test with than:
```
pip install knowledge-repo
knowledge_repo --repo <repo path> runserver
```
What are your thoughts on this?

**Comment by FvD** [comment]
Thanks @matthewwardrop. I had not tried an install from pypi yet.

The reason to set up a Dockerfile is that as soon as I get this running I want to share it with my team. With a working Dockerfile I can deploy with little hassle for us to play around with it as a group. The alternatives are a python virtual environment or a virtual machine, that seemed like more work. Also the Dockerfile instructs me about any dependencies, and I was expecting dependencies other than python, but there seem to be none.

But then again it is not running yet: "Uh oh! Looks like something broke". I have no error messages, and don't know what is missing. The last message in the container terminal is from alembic:

    INFO  [alembic.runtime.migration] Running stamp_revision  -> 1b385158fd32

Can you help and have a look? Any dependencies I have not included?

To use this Dockerfile:

    $ docker build -t knowledgerepo .
    $ docker run --rm -p 7000:7000 --name airbnb -ti knowledgerepo 

This will run the container and land you on the command line, where you can set up a test repository and run the server as per the README file:

    $ knowledge_repo --repo ./example_repo init
    $ knowledge_repo --repo ./example_repo runserver

**Comment by matthewwardrop** [comment]
That makes sense @FvD :).

I'll take a look in parallel, but it might be worth your adding the '--debug' option to your command (`knowledge_repo --repo <> --debug runserver`). This will reveal more informative messages than presently :).

There are some hidden dependencies that are needed only when uploading images via the web editor; but otherwise all dependencies are installed by python. Inside of the docker image one should probably use `pip install "knowledge-repo[all]"`, as this installs all dependencies including those only needed occasionally server-side.

**Comment by matthewwardrop** [comment]
@FvD Looks like the error is due to a recent feature addition related to excluding posts based on tags. We'll fix this shortly.

**Comment by matthewwardrop** [comment]
@FvD : We've fixed these issues now. You should be able to test the Docker image successfully now :).

**Comment by FvD** [comment]
@matthewwardrop I get a new error that seems to be related to the change in concerning tags that you guys have just made. Stacktrace below.

```
root@607e8861855f:/knowledge# knowledge_repo --repo ./test --debug runserver
INFO:alembic.runtime.migration:Context impl SQLiteImpl.
INFO:alembic.runtime.migration:Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running stamp_revision  -> 1b385158fd32
/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/default_comparator.py:161: SAWarning: The IN-predicate on "tags.name" was invoked with an empty sequence. This results in a contradiction, which nonetheless can be expensive to evaluate.  Consider alternative strategies for improved performance.
  'strategies for improved performance.' % expr)
Traceback (most recent call last):
  File "/usr/local/bin/knowledge_repo", line 297, in <module>
    threaded=threaded)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 843, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 694, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 659, in inner
    srv.serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 499, in serve_forever
    HTTPServer.serve_forever(self)
  File "/usr/lib/python2.7/SocketServer.py", line 233, in serve_forever
    self._handle_request_noblock()
  File "/usr/lib/python2.7/SocketServer.py", line 292, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
socket.error: [Errno 32] Broken pipe
```

**Comment by matthewwardrop** [comment]
@FvD This broken pipe is actually a problem with the inbuilt flask web server, which is not designed to handle multiple simultaneous requests. Try `knowledge_repo --repo <> deploy`. This sets up a gunicorn server, which *can* handled multiple requests. `runserver` is designed only for debugging.

**Comment by matthewwardrop** [comment]
Hi @FvD ! How is it going?

Just in case you're having difficulty with this: to get new versions of the knowledge-repo into your image you need to use a so-called "cache-buster"; that is, add the version to knowledge-repo.

i.e. `pip3 install --upgrade "knowledge-repo[all]==0.6.4"`

If you don't do this, docker build will reuse the existing cached image delta.

Also, rather than merging in updates from master, it's a better idea to use git rebase; that way you don't duplicate any commits between your branch and upstream master.

Let me know if you need any help!

Best,
M

**Comment by FvD** [comment]
Thanks @matthewwardrop for the tips. And sorry for messing up the commit history. Please just close this branch when we are done, without merging it. There is no point in adding senseless commits to your master branch log. I have set some time aside to continue experimenting tomorrow.

**Comment by FvD** [comment]
:tada: thanks for your help! I have a working Dockerfile now, and a basis to start playing around. I'm also closing this pull request so that there is no fluff in the commit history. I'll try to make a clean request from a branch, and if that does not work I'll post the working Dockerfile below.

**Comment by npdoty** [comment]
I'm using a basic Dockerfile for deployment of the site; it just needs some customization for the particular knowledge repository.
https://github.com/npdoty/knowledge-repo/blob/master/Dockerfile

It would be great if basic deployment rules/scripts were a standard feature of knowledge-repo, as I'm sure this Dockerfile can be improved. (For example, I should probably be using an nginx reverse proxy in front of gunicorn?)

**Comment by matthewwardrop** [comment]
Thanks for letting us know @npdoty . We are just now internally starting to roll out the knowledge repo using Docker (and Kubernetes) rather than Chef (as we have done previously). We do plan to bolster our documentation regarding deployment; but for now I'll open an issue dedicated to creation (and discussion) of such documentation. :).

**Comment by Analect** [comment]
@matthewwardrop 
> We are just now internally starting to roll out the knowledge repo using Docker (and Kubernetes) 

Would you, by any chance, be able to point me to a working kubernetes manifest for getting knowledge repo running in a kubernetes context?

Thanks.

**Comment by matthewwardrop** [comment]
@Analect Our Kubernetes configuration is reasonably involved :(. We compile a `pex` file, which we then wrap in a Docker image with various filesystem pass-throughs and git repository syncing mechanisms, and then deploy the resulting image to Kubernetes. I'm midway through rewriting/improving our documentation, part of which will be focussed on server-side deployment. I'll try to provide the basis for a working implementation atop Kubernetes, distilled from our complicated set up, as part of this effort.

If you have any special use cases, we can try to help you in your deployment :).

**Comment by Analect** [comment]
@matthewwardrop .. thanks.  I'm just beginning to look at knowledge-repo, so probably not fully aware of the subtle settings that might be required.  I've been working a bit with [git-sync](https://github.com/kubernetes/git-sync) recently for another use-case which involved having an ssh capability from a pod by adding git-sync as a side-car. Some documentation has been added on the subject [here](https://github.com/kubernetes/git-sync/blob/master/docs/ssh.md).  I'd certainly be interested in how you are solving things.

**Pull request closed without merging**
