### PR TITLE
Allow users to load their own Gunicorn config

### PR DESCRIPTION
**Pull request by dmaljovec**
What?
=====

* Port relevant sections of code from `gunicorn.app.base.Application` into `knowledge-repo.app.deploy.gunicorn.GunicornDeployer` to use the `--config` supplied by the user.

Why?
=====

* We'd like to instrument our deployment of Knowledge-Repo with some observability metrics and being able to customize our gunicorn deployment is the way we do that with other apps right now.

This builds off of https://github.com/airbnb/knowledge-repo/pull/437 where a user can supply their own arguments. Unfortunately, while I can see that it does indeed bring in my `GUNICORN_CMD_ARGS='--config gunicorn.conf.py` it does not actually load it up. I stole some code from [gunicorn's source](https://github.com/benoitc/gunicorn/blob/ee685e197b3f7cf899dc7d6e0688ff169e9d10df/gunicorn/app/base.py#L173-L180) and adapted it gently to work in the knowledge-repo use case. Please let me know if this is something you think is worth supporting and if you need anything additional to make this go (tests, more explanation, a usage example, etc.).

### CODE REVIEW

**Comment by dmaljovec** [comment]
I tested this in a test deployment and it appears to do what I want, FWIW.

**Review by naoyak — APPROVED** [review]
Thanks!

**Comment by naoyak** [comment]
@dmaljovec Sorry about the long delay. Is there a way you could add a test?

**Comment by dmaljovec** [comment]
> @dmaljovec Sorry about the long delay. Is there a way you could add a test?

Yeah, sure. I'll try to have a look before the end of the week.

**Comment by dmaljovec** [comment]
Sorry, I took a brief look and it looks like the `GunicornDeployer` is not under test yet (actually, it looks like none of the `KnowledgeDeployer` subclasses are), so it might take more effort than I first thought to write some unit tests around this. I haven't thought much about it and maybe it is easier than I am making it out to be, but it might be some time before I get a chance to think about testing this component in isolation. I was hoping to just plug in some minor modifications of existing tests.

**Pull request merged**
