### PR TITLE
Fix plotly, tags and 'Hide All Code' button for markdown

### PR DESCRIPTION
**Pull request by tanni3009**
Description of changeset: 
Change jquery selectors for renderedMarkdown (was changed from id to class), so that tags and 'Hide All Code' button work again
Add plotly.js as static module and place it before required.js to fix plotly charts in markdown

Test Plan: 

Auto-reviewers: @NiharikaRay @matthewwardrop @earthmancash @danfrankj

### CODE REVIEW

**Comment by matthewwardrop** [comment]
Hi @tanni3009,

Thanks for taking the time to submit a patch to the knowledge repo! The name id->class changes definitely make sense, but including plotly.js (which is a fairly hefty module) indiscriminantly for every post may not be the best way to approach this (especially since some versions are incompatible, and we want old posts to be able to render too). I think by default the plotly offline package includes all the javascript required into the output itself, and hence only needs `require` to be in the javascript namespace. Is that right?

**Comment by tanni3009** [comment]
Hi @matthewwardrop,

Thanks for the answer! You are right, including plotly.js is probably not the best approach. 
I tried to get it to work with require, but to be honest, I've never worked with it before so I'm stuck now. Could you give me some guidance on how to do it?

**Comment by Breaka84** [comment]
Hi @matthewwardrop,

Thanks for your input!
Unfortunately, including the js-code right before the plotly-graph does not work ('Plotly not defined').
To make the markdown-file itself leaner, we normally just include the div without plotly.js.
Maybe it's possible to make loading plotly.js optional? I think about setting a tag while deploying a post, to include plotly.js (before require.js). This would keep backwards compatibility with old posts and allow us to load plotly.js as a static module if needed.

**Comment by matthewwardrop** [comment]
Hey @Breaka84 and @tanni3009,

I took a look into this over the weekend and it looks like the javascript/plotly issues were related to the way that the markdown was converted to HTML. If fixed that issue (and in the process improved the rendering of the cell blocks and outputs, which included the toggle buttons) in #256 . At this stage, I think everything should be working as expected (including Plotly graphs). If it works in the Jupyter notebook, it should work in the knowledge repo.

If you get a chance, can you test this, and if everything is fixed to your satisfaction, feel free to close this PR :).

Best,
M

**Comment by Breaka84** [comment]
Hi Matthew,

thank you for your effort!
Unfortunately, it still doesn't work. It's the same error message: `Plotly is not defined`...
But this PR can be closed as the `tags` and `hide code` button are now fixed!
We (my company) can live with adding the plotly.js statically by using my fork.

Greetings,
David

**Comment by matthewwardrop** [comment]
Hi @tanni3009 @Breaka84,

Just tested the knowledge_repo code again, and plotly seems to work great. Perhaps I'm missing something? This is something we want to support, but given that plotly.offline.init_notebook_mode(connected=True/False) will link to plotly js on a cdn / embed javascript in notebook, I don't think you need to patch knowledge_repo to achieve this. I added a sample knowledge post with Plotly figures here: https://github.com/airbnb/knowledge-repo/blob/master/tests/test_posts/plotly.ipynb .

Let me know if I can be of any further assistance!

M

**Comment by Breaka84** [comment]
Hi @matthewwardrop,

I see now where the root of our misunderstanding lies :-)
Yes, plotly in a jupyter notebook (ipyn) without a hitch, but we are using and having problems with Plotly graphs within simple markdown files (md). I'll try to come up with a simple example to demonstrate the problem.

Best,
David

**Comment by Breaka84** [comment]
Hi @matthewwardrop,

I uploaded some test files which show the problem we were describing with plotly within simple markdown-files at
https://github.com/Breaka84/knowledge-repo/tree/plotly_md_test/tests/test_posts/plotly
Namely `simple_plotly_markdown_with_included_plotly_js_code.md`, `simple_plotly_markdown_with_online_polotly_js.md` & `simple_plotly_markdown_without_plotly_js.md`

Best,
David

**Pull request closed without merging**
