### PR TITLE
Add LDAP authorization

### PR DESCRIPTION
**Pull request by naoyak**
## Description of changeset
Closes #416 with a rebase and separating out commits from #393
Test Plan:

### CODE REVIEW

**Comment by naoyak** [comment]
Is anyone interested in testing out this branch to at least verify that it works? I don't know if @dorianbrown or @manuelaudibene still have any interest in this...

**Comment by dorianbrown** [comment]
Oh, flash from the past, kind of forgot about this one. I've got some time next week to test it. Would a manual test with a dockerized LDAP server be enough? I think I stopped working on this after trying to setup an automated test...

**Comment by naoyak** [comment]
@dorianbrown sure, a manual test would be great!

**Comment by dorianbrown** [comment]
So I've tested it, and authentication is working fine. The only thing I think could use some extra work is returning errors when the ldap settings in the app-config are incorrectly set. 

The one I ran into immediately is using `ldaps` instead of `ldap` for the connection string, and although the ldap3 library is throwing an error, no exceptions are being shown in the webapps stdout.

Is my config of the flask logger wrong, or do we need to do something extra to get these errors visible in the logs?

**Comment by naoyak** [comment]
Hey thanks for testing this @dorianbrown! I'm still a bit new to the quirks of testing the app in development, but it's good to hear it's up and running. Can you provide some example config? I guess worst case you could just throw some print statements in there for the error trace.

**Comment by dorianbrown** [comment]
If you want to test it yourself, you need to

1. spin up [this docker container](https://github.com/rroemhild/docker-test-openldap) as an ldap server
2. Change `AUTH_PROVIDERS` to `['ldap']` in the config file
3. Uncomment `LDAP_SERVER` and set it to `ldap://127.0.0.1:389`

You can then log in with one of the UN/PW combinations like Philip J. Fry/fry. The error happens if you for example use `ldaps://127.0.0.1:389` instead.

I've tried to `self.app.logger.error("some error")`, `print("error")`, and even `self.app.log_exception("some error")` but none of them seem to be visible. I also lack some knowledge as to why this is happening, so I might take some time to try and understand this better.

**Comment by dorianbrown** [comment]
Nevermind, I was running the app in "production mode", when I ran the server in debug mode I was able to see what the error was.

I cleaned up a few things in the branch, but I'm unable to push the changes. Any idea how I can best update this branch?

**Comment by naoyak** [comment]
Hmm sorry, I guess the only easy way is for you to open a new PR. You can either target master or `ldap_auth` branches, whichever works for you, thanks!

**Comment by naoyak** [comment]
Thanks for your help @dorianbrown!!

**Pull request merged**
